on:
  push:
    branches:
      - master
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          npm ci
          npm test
          npm run build
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: node
          package-name: ha-sankey-chart
      - name: Upload Release Artifact
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ steps.release.outputs.tag_name }} ./dist/ha-sankey-chart.js
      - name: HACS Validate
        if: ${{ steps.release.outputs.release_created }}
        uses: hacs/action@main
        with:
          category: plugin