name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        description: Target release tag

permissions: {}

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      # Build
      - name: Build the file
        run: |
          cd /home/runner/work/ha-sankey-chart/ha-sankey-chart
          npm ci
          npm run rollup

      # Upload build file to the releas as an asset.
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@29e53e917877a24fad85510ded594ab3c9ca12de # 2.11.5

        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /home/runner/work/ha-sankey-chart/ha-sankey-chart/dist/ha-sankey-chart.js
          asset_name: ha-sankey-chart.js
          tag: ${{ github.event.inputs.tag || github.ref }}
          overwrite: true
  validate:
    needs: release
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      # - uses: "home-assistant/actions/hassfest@master"
      - name: HACS Validate
        uses: hacs/action@d556e736723344f83838d08488c983a15381059a # 22.5.0
        with:
          category: plugin
